name: caco_flutter_blog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  copy_with_extension_gen: ^11.0.0
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.2.0
  get_it: ^9.2.0
  image_picker: ^1.2.1
  internet_connection_checker_plus: ^2.9.1+2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  supabase_flutter: ^2.12.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  json_serializable: ^6.11.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
